language: objective-c
osx_image: xcode7.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
install:
  - carthage update --platform iOS
script:
  - set -o pipefail
  - xcodebuild test -scheme Validation -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty -c
notifications:
  email: false
